### ISSUE TITLE
LIPS and macros

### ISSUE THREAD

**Issue by jcubic** [schemeweb/web.scheme.org#1]
LIPS Scheme implementation (as per 1.0-Beta) supports `define-macro` and `syntax-rules` (R7RS) it's not perfect but works most of the times, there are still some disabled tests for edge cases related to scope, fixes need to wait for proper expansion time, right now macros are runtime like functions.

It's also Native JS and the name is uppercase LIPS.

I can create PR.

**Comment by lassik** [comment]
Great! Please do.

**Comment by lassik** [comment]
By the way, if you want to make other improvements to the web page, feel free to send them at any time. The pages on scheme.org are not owned by any one person.

**Comment by jcubic** [comment]
Sure, I've just asked on Gamibt gitter chat if it support syntax-rules (R7RS + SRFI-46) which is most likely, if they reply I'll update here. Will also create PR when I find something to fix on other pages.
